apiVersion: v1
kind: Service
metadata:
  name: transaction-app-service
spec:
  selector:
    app: transaction-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer